# Generated by Django 4.2.1 on 2023-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=10000)),
                ("speaker", models.CharField(max_length=10000)),
                ("venue", models.CharField(max_length=10000)),
                ("date", models.DateTimeField()),
                ("qr_code", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="YearGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000)),
            ],
        ),
    ]
