# Generated by Django 4.2.1 on 2023-05-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes"),
        ),
    ]
