# Generated by Django 4.2.1 on 2023-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_event_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("U", "Upcoming Event"), ("P", "Past Event")],
                default="U",
                max_length=50,
                null=True,
            ),
        ),
    ]
